import localFont from 'next/font/local';
import { Poppins } from 'next/font/google';

import { cn } from '@/lib/utils';
import Footer from "@/components/Footer/Footer";
import Header from "@/components/HomePage/Header/Header";
import "@styles/globals.css";

// app/layout.tsx
export const metadata = {
    title: 'My App',
    description: 'Generated by Next.js',
};

const Adorsholipi = localFont({
    src: './fonts/AdorshoLipi/AdorshoLipi.woff2',
    variable: '--adorsho-lipi-font',
});

const Popins = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--popins-font',
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='bn'>
            <body
                className={cn(
                    'antialiased',
                    Adorsholipi.className,
                    Popins.variable
                )}
            >
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
