import Footer from "@/components/Footer/Footer";
import Header from "@/components/HomePage/Header/Header";
import "@styles/globals.css";

// app/layout.tsx
export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
