import React from "react";

const page = () => {
  return (
    <div className="dark:bg-white bg-white">
      <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-20">
        <div className="text-black py-20">
          <div className="border-b-2 border-[#165588] pb-2 w-[30%]">
            <h1 className="text-3xl font-bold text-[#165588]">
              Privacy Policy
            </h1>
          </div>
          <div className="pt-8 space-y-6">
            <div>
              <h1 className="text-2xl font-bold text-[#165588]">License</h1>
              <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use
                the Service and tells You about Your privacy rights and how the
                law protects You. We use Your Personal data to provide and
                improve the Service. By using the Service, You agree to the
                collection and use of information.
              </p>
              <div className="py-3">
                <p className="">
                  accordance with this Privacy Policy:
                </p>
                <ul>
                  <li>Interpretation and Definitions</li>
                  <li>Interpretation</li>
                  <li>
                    The words of which the initial letter is capitalized have
                    meanings defined under the following conditions. The
                    following definitions shall have the same meaning regardless
                    of whether they appear in singular or in plural.
                  </li>
                </ul>
              </div>
              <h1 className="text-2xl font-bold text-[#165588]">Definitions</h1>
              <p className="text-justify">
                <span className="font-bold">
                  For the purposes of this Privacy Policy:
                </span>{" "}
                Account means a unique account created for You to access our
                Service or parts of our Service. Company (referred to as either
                the Company , We, Us or Our in this Agreement) refers to Daily
                Weekly Ajkal, 71-16 35th Ave, Jackson Heights,NY 11372, USA.
                Cookies are small files that are placed on Your computer, mobile
                device or any other device by a website, containing the details
                of Your browsing history on that website among its many uses.
                Country refers to: USA & Bangladesh Device means any device that
                can access the Service such as a computer, a cellphone or a
                digital tablet. Personal Data is any information that relates to
                an identified or identifiable individual. Service refers to the
                Website. Service Provider means any natural or legal person who
                processes the data on behalf of the Company. It refers to
                third-party companies or individuals employed by the Company to
                facilitate the Service, to provide the Service on behalf of the
                Company, to perform services related to the Service or to assist
                the Company in analyzing how the Service is used. Third-party
                Social Media Service refers to any website or any social network
                website through which a User can log in or create an account to
                use the Service. Usage Data refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit). Website refers to Daily Weekly Ajkal,
                accessible from https://ajkalusa.com/
                <span className="font-bold">
                  You means the individual accessing or using the Service, or
                  the company, or other legal entity on behalf of which such
                  individual is accessing or using the Service, as applicable.
                </span>
              </p>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">Usage Data</h1>
                <p className="">
                  Usage Data is collected automatically when using the Service.
                  Usage Data may include information such as Your
                  Device'sInternet Protocol address (e.g. IP address), browser
                  type, browser version, the pages of our Service that You
                  visit, the time and date of Your visit, the time spent on
                  those pages, unique device identifiers and other diagnostic
                  data. When You access the Service by or through a mobile
                  device, We may collect certain information automatically,
                  including, but not limited to, the type of mobile device You
                  use, Your mobile device unique ID, the IP address of Your
                  mobile device, Your mobile operating system, the type of
                  mobile Internet browser You use, unique device identifiers and
                  other diagnostic data. We may also collect information that
                  Your browser sends whenever You visit our Service or when You
                  access the Service by or through a mobile device.
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">
                  Changes to this Privacy Policy
                </h1>
                <p className="">
                  We may update Our Privacy Policy from time to time. We will
                  notify You of any changes by posting the new Privacy Policy on
                  this page. We will let You know via email and/or a prominent
                  notice on Our Service, prior to the change becoming effective
                  and update the Last updated date at the top of this Privacy
                  Policy. You are advised to review this Privacy Policy
                  periodically for any changes. Changes to this Privacy Policy
                  are effective when they are posted on this page.
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">Links to Other Websites</h1>
                <p className="">
                  Our Service may contain links to other websites that are not
                  operated by Us. If You click on a third party link, You will
                  be directed to that third party's site. We strongly advise You
                  to review the Privacy Policy of every site You visit. We have
                  no control over and assume no responsibility for the content,
                  privacy policies or practices of any third party sites or
                  services.
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">Children'sPrivacy</h1>
                <p className="">
                  Our Service does not address anyone under the age of 13. We do
                  not knowingly collect personally identifiable information from
                  anyone under the age of 13. If You are a parent or guardian
                  and You are aware that Your child has provided Us with
                  Personal Data, please contact Us. If We become aware that We
                  have collected Personal Data from anyone under the age of 13
                  without verification of parental consent, We take steps to
                  remove that information from Our servers. If We need to rely
                  on consent as a legal basis for processing Your information
                  and Your country requires consent from a parent, We may
                  require Your parent's consent before We collect and use that
                  information.
                </p>
              </div>
              <div className="py-3">
                <p className="text-2xl font-bold text-[#165588]">Other legal requirements</p>
                <ul>
                  <li>Comply with a legal obligation</li>
                  <li>
                    Protect and defend the rights or property of the Company
                  </li>
                  <li>
                    Prevent or investigate possible wrongdoing in connection
                    with the Service
                  </li>
                  <li>
                    Protect the personal safety of Users of the Service or the
                    public
                  </li>
                  <li>Protect against legal liability</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className="text-black py-20">
          <div className="border-b-2 border-[#165588] pb-2 w-[35%]">
            <h1 className="text-3xl font-bold text-[#165588]">
              গোপনীয়তা নীতি
            </h1>
          </div>
          <div className="pt-8 space-y-6">
            <div>
              <h1 className="text-2xl font-bold text-[#165588]">লাইসেন্স</h1>
              <p>
                এই গোপনীয়তা নীতি আমাদের নীতিমালা এবং আপনার তথ্য সংগ্রহ, ব্যবহার
                এবং প্রকাশের পদ্ধতি বর্ণনা করে, যখন আপনি সেবা ব্যবহার করেন এবং
                আপনাকে আপনার গোপনীয়তা অধিকার এবং আইন কিভাবে আপনাকে সুরক্ষা দেয়
                তা জানায়। আমরা আপনার ব্যক্তিগত তথ্য সেবা প্রদান এবং উন্নত করতে
                ব্যবহার করি। সেবা ব্যবহার করে, আপনি তথ্য সংগ্রহ এবং ব্যবহারে
                সম্মত হন।
              </p>
              <div className="py-3">
                <p className="">এই গোপনীয়তা নীতি অনুযায়ী:</p>
                <ul>
                  <li>ব্যাখ্যা এবং সংজ্ঞা</li>
                  <li>ব্যাখ্যা</li>
                  <li>
                    যে শব্দগুলির প্রথম অক্ষর বড় হয়ে থাকে, তাদের মানে
                    নিম্নলিখিত শর্তাবলীতে সংজ্ঞায়িত হয়েছে। নিম্নলিখিত
                    সংজ্ঞাগুলি একবচন বা বহুবচনে প্রকাশিত হলেও একে অপরের সমান
                    মানে হবে।
                  </li>
                </ul>
              </div>
              <h1 className="text-2xl font-bold text-[#165588]">সংজ্ঞা</h1>
              <p className="text-justify">
                <span className="font-bold">এই গোপনীয়তা নীতির উদ্দেশ্যে:</span>{" "}
                অ্যাকাউন্ট মানে একটি অনন্য অ্যাকাউন্ট যা আপনার জন্য আমাদের সেবা
                বা আমাদের সেবার অংশ অ্যাক্সেস করতে তৈরি করা হয়েছে। কোম্পানি
                (এটি এই চুক্তিতে কোম্পানি, আমরা, আমাদের বা আমাদের নামে উল্লেখিত)
                Daily Weekly Ajkal, 71-16 35th Ave, Jackson Heights, NY 11372,
                USA-কে বোঝায়। কুকি হল ছোট ফাইল যা আপনার কম্পিউটার, মোবাইল
                ডিভাইস বা অন্য কোনো ডিভাইসে স্থাপন করা হয়, যা সেই ওয়েবসাইটে
                আপনার ব্রাউজিং ইতিহাসের বিশদ তথ্য ধারণ করে। দেশ মানে: USA এবং
                বাংলাদেশ। ডিভাইস মানে সেই ডিভাইস যা সেবা অ্যাক্সেস করতে পারে
                যেমন কম্পিউটার, মোবাইল ফোন বা ডিজিটাল ট্যাবলেট। ব্যক্তিগত তথ্য
                হল এমন কোনো তথ্য যা একটি চিহ্নিত বা চিহ্নিতযোগ্য ব্যক্তির সাথে
                সম্পর্কিত। সেবা মানে হলো ওয়েবসাইট। সেবা প্রদানকারী মানে কোনো
                প্রাকৃতিক বা আইনি ব্যক্তি যারা কোম্পানির পক্ষ থেকে ডেটা
                প্রক্রিয়া করে। এটি তৃতীয় পক্ষের কোম্পানি বা ব্যক্তিদের বোঝায়
                যারা সেবা সুবিধার্থে, কোম্পানির পক্ষ থেকে সেবা প্রদান করতে, সেবা
                সম্পর্কিত পরিষেবা করতে বা সেবার ব্যবহার বিশ্লেষণ করতে কোম্পানির
                সাহায্য করে। তৃতীয় পক্ষের সামাজিক মিডিয়া সেবা মানে এমন কোনো
                ওয়েবসাইট বা সামাজিক নেটওয়ার্ক সাইট যার মাধ্যমে একটি ব্যবহারকারী
                লগ ইন করতে পারে বা সেবা ব্যবহার করতে অ্যাকাউন্ট তৈরি করতে পারে।
                ব্যবহার ডেটা হল স্বয়ংক্রিয়ভাবে সংগৃহীত তথ্য, যা সেবার
                ব্যবহারের মাধ্যমে বা সেবা পরিকাঠামো থেকেই প্রাপ্ত হতে পারে
                (যেমন, পৃষ্ঠায় সময়)। ওয়েবসাইট মানে Daily Weekly Ajkal, যা
                https://ajkalusa.com/ থেকে প্রবেশযোগ্য।
                <span className="font-bold">
                  আপনি মানে সেই ব্যক্তি যিনি সেবা অ্যাক্সেস করছেন বা ব্যবহার
                  করছেন, অথবা কোম্পানি, বা অন্য কোন আইনি সত্ত্বা যার পক্ষ থেকে
                  সেই ব্যক্তি সেবা অ্যাক্সেস বা ব্যবহার করছে, যা প্রযোজ্য।
                </span>
              </p>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">ব্যবহার ডেটা</h1>
                <p className="">
                  ব্যবহার ডেটা স্বয়ংক্রিয়ভাবে সেবা ব্যবহারের সময় সংগৃহীত হয়।
                  ব্যবহার ডেটায় আপনার ডিভাইসের ইন্টারনেট প্রোটোকল (IP) ঠিকানা
                  (যেমন IP ঠিকানা), ব্রাউজার টাইপ, ব্রাউজার সংস্করণ, আমাদের
                  সেবার যেসব পৃষ্ঠায় আপনি যান, আপনার দর্শনের সময় এবং তারিখ,
                  আপনি যেসব পৃষ্ঠায় সময় ব্যয় করেছেন, অনন্য ডিভাইস শনাক্তকারী
                  এবং অন্যান্য ডায়াগনস্টিক তথ্য অন্তর্ভুক্ত থাকতে পারে। যখন
                  আপনি মোবাইল ডিভাইসের মাধ্যমে সেবা অ্যাক্সেস করেন, আমরা কিছু
                  নির্দিষ্ট তথ্য স্বয়ংক্রিয়ভাবে সংগ্রহ করতে পারি, যার মধ্যে,
                  কিন্তু সীমাবদ্ধ নয়, আপনার মোবাইল ডিভাইসের ধরন, আপনার মোবাইল
                  ডিভাইসের ইউনিক আইডি, আপনার মোবাইল ডিভাইসের IP ঠিকানা, আপনার
                  মোবাইল অপারেটিং সিস্টেম, আপনি যে মোবাইল ইন্টারনেট ব্রাউজারটি
                  ব্যবহার করেন, অনন্য ডিভাইস শনাক্তকারী এবং অন্যান্য
                  ডায়াগনস্টিক তথ্য। আমরা এমন তথ্যও সংগ্রহ করতে পারি যা আপনার
                  ব্রাউজার আমাদের সেবায় যখন আপনি যান, অথবা যখন আপনি মোবাইল
                  ডিভাইসের মাধ্যমে সেবা অ্যাক্সেস করেন তখন আপনার ব্রাউজার
                  পাঠায়।
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">
                  এই গোপনীয়তা নীতিতে পরিবর্তন
                </h1>
                <p className="">
                  আমরা আমাদের গোপনীয়তা নীতিটি সময়ে সময়ে আপডেট করতে পারি। আমরা
                  আপনাকে নতুন গোপনীয়তা নীতি এই পৃষ্ঠায় পোস্ট করে জানাবো।
                  পরিবর্তন কার্যকর হওয়ার আগে আমরা আপনাকে ইমেল এবং/অথবা আমাদের
                  সেবায় একটি স্পষ্ট নোটিশ দ্বারা জানাবো এবং গোপনীয়তা নীতির
                  শীর্ষে সর্বশেষ আপডেট তারিখ আপডেট করব। আপনাকে গোপনীয়তা নীতিটি
                  সময়ে সময়ে পর্যালোচনা করার পরামর্শ দেওয়া হচ্ছে। গোপনীয়তা
                  নীতিতে পরিবর্তনগুলি যখন এই পৃষ্ঠায় পোস্ট করা হয় তখনই কার্যকর
                  হয়।
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">
                  অন্যান্য ওয়েবসাইটে লিঙ্ক
                </h1>
                <p className="">
                  আমাদের সেবায় অন্যান্য ওয়েবসাইটে লিঙ্ক থাকতে পারে যা আমাদের
                  দ্বারা পরিচালিত হয় না। আপনি যদি তৃতীয় পক্ষের লিঙ্কে ক্লিক
                  করেন, তাহলে আপনি সেই তৃতীয় পক্ষের সাইটে পরিচালিত হবেন। আমরা
                  আপনাকে পরামর্শ দিচ্ছি যে আপনি যে সাইটে যান তার গোপনীয়তা নীতি
                  পর্যালোচনা করুন। আমরা তৃতীয় পক্ষের সাইট বা সেবার কনটেন্ট,
                  গোপনীয়তা নীতি বা চর্চা সম্পর্কে কোনো নিয়ন্ত্রণ রাখি না এবং
                  কোনো দায়িত্ব নেবো না।
                </p>
              </div>
              <div className="py-3">
                <h1 className="text-2xl font-bold text-[#165588]">শিশুদের গোপনীয়তা</h1>
                <p className="">
                  আমাদের সেবা ১৩ বছরের নিচের কাউকে লক্ষ্য করে না। আমরা জানব না
                  করে ১৩ বছরের নিচে কোনো ব্যক্তিগত পরিচয়যোগ্য তথ্য সংগ্রহ করি
                  না। যদি আপনি একজন অভিভাবক বা অভিভাবিকা হন এবং আপনি জানেন যে
                  আপনার সন্তান আমাদেরকে ব্যক্তিগত তথ্য দিয়েছে, অনুগ্রহ করে
                  আমাদের সাথে যোগাযোগ করুন। যদি আমরা জানতে পারি যে আমরা
                  অভিভাবকের সম্মতি ছাড়া ১৩ বছরের নিচে কোনো ব্যক্তিগত তথ্য
                  সংগ্রহ করেছি, তবে আমরা সেই তথ্য আমাদের সার্ভার থেকে মুছে ফেলব।
                  যদি আমাদের তথ্য প্রক্রিয়া করার জন্য সম্মতি প্রয়োজন হয় এবং
                  আপনার দেশের আইন অনুযায়ী অভিভাবকের সম্মতি প্রয়োজন, তবে আমরা
                  তথ্য সংগ্রহ এবং ব্যবহার করার আগে আপনার অভিভাবকের সম্মতি নিতে
                  পারি।
                </p>
              </div>
              <div className="py-3">
                <p className="text-2xl font-bold text-[#165588]">অন্যান্য আইনি প্রয়োজনীয়তা</p>
                <ul>
                  <li>আইনি বাধ্যবাধকতা পূর্ণ করা</li>
                  <li>কোম্পানির অধিকার বা সম্পত্তি রক্ষা এবং প্রতিরক্ষা করা</li>
                  <li>
                    সেবার সাথে সম্পর্কিত সম্ভাব্য অন্যায় তদন্ত বা প্রতিরোধ করা
                  </li>
                  <li>
                    সেবা ব্যবহারকারীদের বা জনগণের ব্যক্তিগত নিরাপত্তা রক্ষা করা
                  </li>
                  <li>আইনি দায়িত্ব থেকে রক্ষা করা</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default page;
